# -*- coding: utf-8 -*-
"""
Creates .gdf file for input to Gephi
"""

import pandas
import numpy


def main():

    K = 250 # match to Batchdriver.py
    H = numpy.genfromtxt('results/H_2025-08-31_07-43-11.txt') # H file in results/
    OUT_FILE = 'results/graph.gdf'
    HT = H.T

    # paste in from output of Batchdriver.py
    fn = {
        0: 'positive+negative',
        1: 'shap',
        2: 'deploy+model',
        3: 'validation',
        4: 'problem',
        5: 'reproduce',
        6: 'node+target',
        7: 'world+real',
        8: 'vehicle+uber',
        9: 'matrix+factorization',
        10: 'machinelearning',
        11: 'attacker+malicious',
        12: 'bad+actor',
        13: 'train+xgb',
        14: 'evasion+physical',
        15: 'design+experimental',
        16: 'regression+penalize',
        17: 'show',
        18: 'credit+card',
        19: 'quality+equivalent',
        20: 'iso+guidance',
        21: 'seed+underspecification',
        22: 'dataset',
        23: 'team',
        24: 'product+maker',
        25: 'xgboost',
        26: 'extraction+model',
        27: 'safety',
        28: 'guidance+bank',
        29: 'column+hide',
        30: 'practice+authoritative',
        31: 'data+reader',
        32: 'review+peer',
        33: 'statistical+significance',
        34: 'model',
        35: 'shapley+python',
        36: 'failure+mode',
        37: 'accuracy+neural',
        38: 'performance',
        39: 'engineer+datascientists',
        40: 'case+study',
        41: 'application+risk',
        42: 'highlight+binary',
        43: 'focus+treat',
        44: 'legal+regulatory',
        45: 'analysis',
        46: 'glm+offensive',
        47: 'robustness+subpopulation',
        48: 'input',
        49: 'external+internal',
        50: 'evaluate+slim',
        51: 'triad+cia',
        52: 'prediction',
        53: 'region+lung',
        54: 'debug',
        55: 'rule',
        56: 'remediation',
        57: 'data+breach',
        58: 'perturbation+dependent',
        59: 'structure+incentive',
        60: 'artificialintelligence',
        61: 'project+diverse',
        62: 'sensitivity+analysis',
        63: 'path+mojo',
        64: 'poison+data',
        65: 'crop+preserve',
        66: 'incident',
        67: 'domain+knowledge',
        68: 'explainable',
        69: 'causal+inference',
        70: 'repayment+drink',
        71: 'idea',
        72: 'control',
        73: 'customer+payment',
        74: 'zillow+ibuying',
        75: 'company+independent',
        76: 'environment+track',
        77: 'harm',
        78: 'target+corr',
        79: 'loss+entropy',
        80: 'fold',
        81: 'overfit+unreliable',
        82: 'constrain+model',
        83: 'organizational+accountability',
        84: 'stress+recession',
        85: 'augmentation+create',
        86: 'procedure+iteration',
        87: 'consumer+finance',
        88: 'science+data',
        89: 'importance+global',
        90: 'transparency+cluster',
        91: 'technique',
        92: 'gbm+payment',
        93: 'delinq+violin',
        94: 'complex',
        95: 'adversarial',
        96: 'correlation+spearman',
        97: 'dependence+ice',
        98: 'map',
        99: 'robust+swing',
        100: 'choice+deliberate',
        101: 'disparate+treatment',
        102: 'package+research',
        103: 'interpretable',
        104: 'training',
        105: 'smd+practical',
        106: 'govern',
        107: 'output',
        108: 'payment+drift',
        109: 'remediate',
        110: 'data',
        111: 'build+disability',
        112: 'point+life',
        113: 'gam+additive',
        114: 'traditional+equivalent',
        115: 'default+hispanic',
        116: 'tree',
        117: 'algorithm+machinelearning',
        118: 'organization+machinelearning',
        119: 'simulate+api',
        120: 'appeal+override',
        121: 'anomaly+detection',
        122: 'color+digital',
        123: 'book',
        124: 'occlusion+patch',
        125: 'technology+company',
        126: 'challenge+effective',
        127: 'learn',
        128: 'shortcut+fail',
        129: 'lime+local',
        130: 'countermeasure',
        131: 'probability+default',
        132: 'level+significance',
        133: 'overfitting+variance',
        134: 'objective+optimization',
        135: 'trust+transparency',
        136: 'air+hispanic',
        137: 'boost+machine',
        138: 'tool+track',
        139: 'fairness+aware',
        140: 'business+assertion',
        141: 'cutoff+lend',
        142: 'deep+neural',
        143: 'differential+validity',
        144: 'outcome',
        145: 'nist+framework',
        146: 'linear+summarize',
        147: 'extract+api',
        148: 'fix+bug',
        149: 'amt',
        150: 'parameter+penalty',
        151: 'weight',
        152: 'perform+drift',
        153: 'histogram+conditional',
        154: 'construct+validity',
        155: 'system+machinelearning',
        156: 'attack',
        157: 'measure',
        158: 'test',
        159: 'auc+treat',
        160: 'face+discrimination',
        161: 'audit+exercise',
        162: 'decision',
        163: 'interaction+degree',
        164: 'chapter',
        165: 'residual+logloss',
        166: 'data+federate',
        167: 'lambda+alpha',
        168: 'representation+space',
        169: 'assessment+impact',
        170: 'grade+implement',
        171: 'constraint+monotonic',
        172: 'label+noisy',
        173: 'round+evals',
        174: 'experience',
        175: 'expert+index',
        176: 'mitigate+factor',
        177: 'experiment+track',
        178: 'class+imbalance',
        179: 'practitioner+paper',
        180: 'figure',
        181: 'impact+cluster',
        182: 'risk+cluster',
        183: 'pneumonia+patient',
        184: 'scientific+confirmation',
        185: 'classifier+pytorch',
        186: 'local+applicant',
        187: 'documentation+model',
        188: 'human',
        189: 'ebm+bal',
        190: 'inference+hacker',
        191: 'classification+binary',
        192: 'bug+bounty',
        193: 'plot',
        194: 'observation+reference',
        195: 'random',
        196: 'hoc',
        197: 'datasets+leakage',
        198: 'security',
        199: 'vulnerability+public',
        200: 'rmf+artificialintelligence',
        201: 'calculate+threshold',
        202: 'setting+holdout',
        203: 'resource',
        204: 'proxy+suspect',
        205: 'mitigation+governance',
        206: 'step+stakeholder',
        207: 'concept+refresher',
        208: 'regularization+strength',
        209: 'error',
        210: 'patient+healthcare',
        211: 'important',
        212: 'surrogate',
        213: 'drive+applicant',
        214: 'school+feel',
        215: 'gradient+integrate',
        216: 'estimate+money',
        217: 'mrm+cultural',
        218: 'noise+injection',
        219: 'privacy+law',
        220: 'risk+data',
        221: 'diversity+study',
        222: 'improve+accurate',
        223: 'grid+glm',
        224: 'backdoor+branch',
        225: 'protect+prohibit',
        226: 'monitor',
        227: 'assumption+hyperparameters',
        228: 'future+context',
        229: 'ice+curve',
        230: 'student+school',
        231: 'race+scale',
        232: 'metric',
        233: 'software+dependency',
        234: 'true+negative',
        235: 'demographic+marker',
        236: 'effect+rashomon',
        237: 'bias',
        238: 'score',
        239: 'pay',
        240: 'instability+sparse',
        241: 'statistics+data',
        242: 'prototype+cluster',
        243: 'law+act',
        244: 'predict',
        245: 'behavior+observe',
        246: 'rank',
        247: 'explainability+interpretability',
        248: 'social+media',
        249: 'deployment+chance'
    }
    HTCorr = pandas.DataFrame(HT, columns=fn).corr().to_numpy()

    with open(OUT_FILE, 'w+') as out_file_:
        out_file_.write('nodedef>name VARCHAR,label VARCHAR\n')
        for i in range(0, K):
            out_file_.write(str(i) + ',' + fn[i] + '\n')

        out_file_.write('edgedef>node1 VARCHAR,node2 VARCHAR, weight DOUBLE\n')
        for i in range(0, K):
            for j in range(0, K):
                if HTCorr[i,j] > 0.1 and i != j:
                    out_file_.write(str(i) + ',' + str(j) + ',' +\
                                        str(HTCorr[i, j]) + '\n')


if __name__ == '__main__':
    main()

